# Set Jekyll
destination: '../archfish.github.io'
timezone: 'Asia/Shanghai'

# Site settings
title: 韦初一的小窝
SEOTitle: Archfish | Blog
header-img: img/home-bg.jpg
email: archfish@gmail.com
description: "精于心 简于形"
keyword: ""
url: "https://archfish.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     archfish
# zhihu_username:     archfish
github_username:    archfish
github_repo:    'archfish'
# twitter_username:   archfish
#facebook_username:  archfish
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: [
  "less", "node_modules", "Gruntfile.js", "package.json",
  "README.md", "README.zh.md", 'package-lock.json',
  'tool.rb', 'Gemfile', 'Gemfile.lock'
]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username:

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me
gsv: 'HUq9zIqmlLMHO-Ns9tEu6drasagknezrT2z0ispbmA8'

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-small.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
# friends: [
#   {
#     title: "",
#     href: ""
#   }
# ]
